const PARTNERS = [
    { id: 'p1', name: "Felipe 'Load'", nickname: "@loadcomics", image: "partners.jpg", link: "#" },
    { id: 'p2', name: "Juliana Alencar", nickname: "@jupadawan", image: "partners.jpg", link: "#" },
    { id: 'p3', name: "Leo Kitsune", nickname: "@leokitsune", image: "partners.jpg", link: "#" },
    { id: 'p4', name: "Erika Kawaii", nickname: "@erikawai", image: "partners.jpg", link: "#" },
    { id: 'p5', name: "Lucas Vlogs", nickname: "@techvlog", image: "partners.jpg", link: "#" },
    { id: 'p6', name: "Mariana Geek", nickname: "@magamer", image: "partners.jpg", link: "#" },
    { id: 'p7', name: "Parceiro Sete", nickname: "@parceiro7", image: "partners.jpg", link: "#" },
    { id: 'p8', name: "Parceiro Oito", nickname: "@parceiro8", image: "partners.jpg", link: "#" },
    { id: 'p9', name: "Parceiro Nove", nickname: "@parceiro9", image: "partners.jpg", link: "#" },
    { id: 'p10', name: "Parceiro Dez", nickname: "@parceiro10", image: "partners.jpg", link: "#" },
    { id: 'p11', name: "Parceiro Onze", nickname: "@parceiro11", image: "partners.jpg", link: "#" },
    { id: 'p12', name: "Parceiro Doze", nickname: "@parceiro12", image: "partners.jpg", link: "#" },
    { id: 'p13', name: "Parceiro Treze", nickname: "@parceiro13", image: "partners.jpg", link: "#" },
    { id: 'p14', name: "Parceiro Catorze", nickname: "@parceiro14", image: "partners.jpg", link: "#" },
    { id: 'p15', name: "Parceiro Quinze", nickname: "@parceiro15", image: "partners.jpg", link: "#" },
    { id: 'p16', name: "Parceiro Dezesseis", nickname: "@parceiro16", image: "partners.jpg", link: "#" },
    { id: 'p17', name: "Parceiro Dezessete", nickname: "@parceiro17", image: "partners.jpg", link: "#" },
    { id: 'p18', name: "Parceiro Dezoito", nickname: "@parceiro18", image: "partners.jpg", link: "#" },
    { id: 'p19', name: "Parceiro Dezenove", nickname: "@parceiro19", image: "partners.jpg", link: "#" },
    { id: 'p20', name: "Parceiro Vinte", nickname: "@parceiro20", image: "partners.jpg", link: "#" },
    { id: 'p21', name: "Parceiro Vinte e Um", nickname: "@parceiro21", image: "partners.jpg", link: "#" },
    { id: 'p22', name: "Parceiro Vinte e Dois", nickname: "@parceiro22", image: "partners.jpg", link: "#" },
    { id: 'p23', name: "Parceiro Vinte e Três", nickname: "@parceiro23", image: "partners.jpg", link: "#" },
    { id: 'p24', name: "Parceiro Vinte e Quatro", nickname: "@parceiro24", image: "partners.jpg", link: "#" },
    { id: 'p25', name: "Parceiro Vinte e Cinco", nickname: "@parceiro25", image: "partners.jpg", link: "#" },
    { id: 'p26', name: "Parceiro Vinte e Seis", nickname: "@parceiro26", image: "partners.jpg", link: "#" },
    { id: 'p27', name: "Parceiro Vinte e Sete", nickname: "@parceiro27", image: "partners.jpg", link: "#" },
    { id: 'p28', name: "Parceiro Vinte e Oito", nickname: "@parceiro28", image: "partners.jpg", link: "#" },
    { id: 'p29', name: "Parceiro Vinte e Nove", nickname: "@parceiro29", image: "partners.jpg", link: "#" },
    { id: 'p30', name: "Parceiro Trinta", nickname: "@parceiro30", image: "partners.jpg", link: "#" }
];