const PRODUCTS = [
    {
        id: 'tshirt-1',
        image: 'Imagens/Fotos Camisas/tshirt-saitama.png',
        name: 'T-Shirt Saitama also Kicks',
        price: 89.90,
        rating: 4.8,
        reviews: 257,
        collection: 'Animes',
        sizes: ['PP', 'P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Cinza', 'Branco'],
        coupon: 'KANGAR10',
        stock: 20,
        tags: ['t-shirt', 'saitama', 'one punch man', 'camisas', 'anime', 'nerd', 'geek', 'preta', 'branca']
    },
    {
        id: 'tshirt-2',
        image: 'Imagens/Fotos Camisas/tshirt-draken.png',
        name: 'T-shirt Tokyo Revengers Draken',
        price: 89.90,
        rating: 4.5,
        reviews: 198,
        collection: 'Animes',
        sizes: ['PP', 'P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Branco', 'Preto'],
        coupon: 'KANGAR10',
        stock: 15,
        tags: ['t-shirt', 'draken', 'tokyo revengers', 'camisas', 'anime', 'geek', 'branca', 'preta']
    },
    {
        id: 'hoodie-3',
        image: 'Imagens/Fotos Camisas/hoodie-akatsuki.png',
        name: 'Hoodie Naruto - Akatsuki Cloud',
        price: 179.90,
        rating: 4.9,
        reviews: 82,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Moletom 3 cabos (Algodão/Poliéster)',
        colors: ['Vermelho', 'Preto'],
        coupon: 'KANGAR10',
        stock: 10,
        tags: ['hoodie', 'moletom', 'naruto', 'akatsuki', 'nuvem', 'anime', 'geek', 'preta']
    },
    {
        id: 'tshirt-4',
        image: 'Imagens/Fotos Camisas/tshirt-guts.png',
        name: 'T-shirt Berserk - Guts Minimal',
        price: 89.90,
        rating: 4.7,
        reviews: 312,
        collection: 'Animes',
        sizes: ['PP', 'P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Cinza'],
        coupon: 'KANGAR10',
        stock: 25,
        tags: ['t-shirt', 'berserk', 'guts', 'camisas', 'minimalista', 'anime', 'nerd', 'preta']
    },
    {
        id: 'tshirt-5',
        image: 'Imagens/Fotos Camisas/tshirt-killua.png',
        name: 'T-shirt Hunter x Hunter - Killua Godspeed',
        price: 99.90,
        rating: 4.9,
        reviews: 101,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão Egípcio',
        colors: ['Azul', 'Preto', 'Cinza'],
        coupon: 'KANGAR10',
        stock: 12,
        tags: ['t-shirt', 'hunter x hunter', 'killua', 'godspeed', 'camisas', 'anime', 'geek', 'preta']
    },
    // --- PRODUTOS 6-30 (PLACEHOLDERS) ---
    {
        id: 'tshirt-6',
        image: 'Imagens/Fotos Camisas/tshirt-saitama.png', 
        name: 'T-Shirt One Piece - Luffy Gear 5',
        price: 94.90,
        rating: 4.6,
        reviews: 150,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão fio 40.1',
        colors: ['Branco', 'Preto'],
        coupon: 'KANGAR10',
        stock: 18,
        tags: ['t-shirt', 'one piece', 'luffy', 'gear 5', 'camisas', 'anime', 'geek', 'branca', 'preta']
    },
    {
        id: 'tshirt-7',
        image: 'Imagens/Fotos Camisas/tshirt-draken.png', 
        name: 'T-Shirt Jujutsu Kaisen - Gojo',
        price: 89.90,
        rating: 4.8,
        reviews: 210,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Branco'],
        coupon: 'KANGAR10',
        stock: 22,
        tags: ['t-shirt', 'jujutsu kaisen', 'gojo satoru', 'camisas', 'anime', 'nerd', 'preta', 'branca']
    },
    {
        id: 'hoodie-8',
        image: 'Imagens/Fotos Camisas/hoodie-akatsuki.png', 
        name: 'Hoodie Attack on Titan - Tropa de Exploração',
        price: 189.90,
        rating: 4.7,
        reviews: 95,
        collection: 'Animes',
        sizes: ['P', 'M', 'G'],
        material: 'Moletom 3 cabos (Algodão/Poliéster)',
        colors: ['Verde', 'Preto'],
        coupon: 'KANGAR10',
        stock: 8,
        tags: ['hoodie', 'moletom', 'attack on titan', 'shingeki', 'tropa', 'anime', 'geek', 'preta']
    },
    {
        id: 'tshirt-9',
        image: 'Imagens/Fotos Camisas/tshirt-guts.png', 
        name: 'T-Shirt Demon Slayer - Rengoku',
        price: 89.90,
        rating: 4.6,
        reviews: 130,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Laranja'],
        coupon: 'KANGAR10',
        stock: 17,
        tags: ['t-shirt', 'demon slayer', 'kimetsu no yaiba', 'rengoku', 'camisas', 'anime', 'nerd', 'preta']
    },
    {
        id: 'tshirt-10',
        image: 'Imagens/Fotos Camisas/tshirt-killua.png', 
        name: 'T-Shirt Evangelion - EVA-01',
        price: 99.90,
        rating: 4.5,
        reviews: 115,
        collection: 'Animes',
        sizes: ['M', 'G', 'GG', 'XG'],
        material: 'Algodão Egípcio',
        colors: ['Preto', 'Roxo'],
        coupon: 'KANGAR10',
        stock: 14,
        tags: ['t-shirt', 'evangelion', 'eva-01', 'shinji', 'camisas', 'anime', 'geek', 'preta']
    },
    {
        id: 'tshirt-11',
        image: 'Imagens/Fotos Camisas/tshirt-saitama.png', 
        name: 'T-Shirt Dragon Ball - Goku Instinto Superior',
        price: 89.90,
        rating: 4.7,
        reviews: 180,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão fio 40.1',
        colors: ['Branco', 'Preto', 'Azul'],
        coupon: 'KANGAR10',
        stock: 30,
        tags: ['t-shirt', 'dragon ball', 'goku', 'dbs', 'camisas', 'anime', 'nerd', 'branca', 'preta']
    },
    {
        id: 'tshirt-12',
        image: 'Imagens/Fotos Camisas/tshirt-draken.png', 
        name: 'T-Shirt Chainsaw Man - Pochita',
        price: 94.90,
        rating: 4.8,
        reviews: 220,
        collection: 'Animes',
        sizes: ['PP', 'P', 'M', 'G'],
        material: 'Algodão fio 40.1',
        colors: ['Laranja', 'Preto'],
        coupon: 'KANGAR10',
        stock: 25,
        tags: ['t-shirt', 'chainsaw man', 'pochita', 'denji', 'camisas', 'anime', 'geek', 'preta']
    },
    {
        id: 'hoodie-13',
        image: 'Imagens/Fotos Camisas/hoodie-akatsuki.png', 
        name: 'Hoodie Jujutsu Kaisen - Sukuna',
        price: 179.90,
        rating: 4.9,
        reviews: 105,
        collection: 'Animes',
        sizes: ['M', 'G', 'GG'],
        material: 'Moletom 3 cabos (Algodão/Poliéster)',
        colors: ['Preto', 'Vermelho'],
        coupon: 'KANGAR10',
        stock: 11,
        tags: ['hoodie', 'moletom', 'jujutsu kaisen', 'sukuna', 'anime', 'nerd', 'preta']
    },
    {
        id: 'tshirt-14',
        image: 'Imagens/Fotos Camisas/tshirt-guts.png', 
        name: 'T-Shirt Death Note - Ryuk',
        price: 89.90,
        rating: 4.6,
        reviews: 160,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Preto'],
        coupon: 'KANGAR10',
        stock: 19,
        tags: ['t-shirt', 'death note', 'ryuk', 'kira', 'camisas', 'anime', 'geek', 'preta']
    },
    {
        id: 'tshirt-15',
        image: 'Imagens/Fotos Camisas/tshirt-killua.png', 
        name: 'T-Shirt Cowboy Bebop - Spike',
        price: 99.90,
        rating: 4.7,
        reviews: 90,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão Egípcio',
        colors: ['Azul', 'Preto'],
        coupon: 'KANGAR10',
        stock: 13,
        tags: ['t-shirt', 'cowboy bebop', 'spike spiegel', 'camisas', 'vintage', 'anime', 'nerd', 'preta']
    },
    {
        id: 'tshirt-16',
        image: 'Imagens/Fotos Camisas/tshirt-saitama.png', 
        name: 'T-Shirt Cavaleiros do Zodíaco - Seiya',
        price: 89.90,
        rating: 4.5,
        reviews: 110,
        collection: 'Animes',
        sizes: ['P', 'M', 'G'],
        material: 'Algodão fio 40.1',
        colors: ['Branco', 'Azul'],
        coupon: 'KANGAR10',
        stock: 15,
        tags: ['t-shirt', 'saint seiya', 'cdz', 'seiya', 'camisas', 'anime', 'geek', 'branca']
    },
    {
        id: 'tshirt-17',
        image: 'Imagens/Fotos Camisas/tshirt-draken.png', 
        name: 'T-Shirt Yu Yu Hakusho - Yusuke',
        price: 89.90,
        rating: 4.6,
        reviews: 99,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão fio 40.1',
        colors: ['Verde', 'Preto'],
        coupon: 'KANGAR10',
        stock: 14,
        tags: ['t-shirt', 'yu yu hakusho', 'yusuke', 'camisas', 'vintage', 'anime', 'nerd', 'preta']
    },
    {
        id: 'hoodie-18',
        image: 'Imagens/Fotos Camisas/hoodie-akatsuki.png', 
        name: 'Hoodie My Hero Academia - U.A.',
        price: 169.90,
        rating: 4.7,
        reviews: 75,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Moletom 3 cabos (Algodão/Poliéster)',
        colors: ['Azul', 'Cinza'],
        coupon: 'KANGAR10',
        stock: 10,
        tags: ['hoodie', 'moletom', 'boku no hero', 'my hero academia', 'ua', 'anime', 'geek']
    },
    {
        id: 'tshirt-19',
        image: 'Imagens/Fotos Camisas/tshirt-guts.png', 
        name: 'T-Shirt Bleach - Ichigo Hollow',
        price: 94.90,
        rating: 4.8,
        reviews: 140,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Branco'],
        coupon: 'KANGAR10',
        stock: 20,
        tags: ['t-shirt', 'bleach', 'ichigo', 'hollow', 'camisas', 'anime', 'nerd', 'preta', 'branca']
    },
    {
        id: 'tshirt-20',
        image: 'Imagens/Fotos Camisas/tshirt-killua.png', 
        name: 'T-Shirt Fullmetal Alchemist - Transmutação',
        price: 99.90,
        rating: 4.7,
        reviews: 125,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão Egípcio',
        colors: ['Preto', 'Vermelho', 'Branco'],
        coupon: 'KANGAR10',
        stock: 16,
        tags: ['t-shirt', 'fullmetal alchemist', 'fma', 'alquimia', 'camisas', 'anime', 'geek', 'preta', 'branca']
    },
    {
        id: 'tshirt-21',
        image: 'Imagens/Fotos Camisas/tshirt-saitama.png', 
        name: 'T-Shirt Vagabond - Musashi',
        price: 99.90,
        rating: 4.9,
        reviews: 190,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão Egípcio',
        colors: ['Preto', 'Branco'],
        coupon: 'KANGAR10',
        stock: 15,
        tags: ['t-shirt', 'vagabond', 'musashi', 'manga', 'camisas', 'anime', 'nerd', 'preta', 'branca']
    },
    {
        id: 'tshirt-22',
        image: 'Imagens/Fotos Camisas/tshirt-draken.png', 
        name: 'T-Shirt Mob Psycho 100 - ???%',
        price: 89.90,
        rating: 4.7,
        reviews: 85,
        collection: 'Animes',
        sizes: ['P', 'M', 'G'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Azul'],
        coupon: 'KANGAR10',
        stock: 10,
        tags: ['t-shirt', 'mob psycho 100', 'mob', 'camisas', 'anime', 'geek', 'preta']
    },
    {
        id: 'hoodie-23',
        image: 'Imagens/Fotos Camisas/hoodie-akatsuki.png', 
        name: 'Hoodie One Piece - Barbanegra',
        price: 179.90,
        rating: 4.6,
        reviews: 60,
        collection: 'Animes',
        sizes: ['M', 'G', 'GG', 'XG'],
        material: 'Moletom 3 cabos (Algodão/Poliéster)',
        colors: ['Preto'],
        coupon: 'KANGAR10',
        stock: 7,
        tags: ['hoodie', 'moletom', 'one piece', 'barbanegra', 'teach', 'anime', 'nerd', 'preta']
    },
    {
        id: 'tshirt-24',
        image: 'Imagens/Fotos Camisas/tshirt-guts.png', 
        name: 'T-Shirt Haikyuu!! - Karasuno',
        price: 89.90,
        rating: 4.5,
        reviews: 102,
        collection: 'Animes',
        sizes: ['PP', 'P', 'M', 'G', 'GG'],
        material: 'Algodão fio 40.1',
        colors: ['Laranja', 'Preto'],
        coupon: 'KANGAR10',
        stock: 20,
        tags: ['t-shirt', 'haikyuu', 'karasuno', 'volei', 'camisas', 'anime', 'geek', 'preta']
    },
    {
        id: 'tshirt-25',
        image: 'Imagens/Fotos Camisas/tshirt-killua.png', 
        name: 'T-Shirt Kaisen - Logo Simples',
        price: 79.90,
        rating: 4.3,
        reviews: 50,
        collection: 'Animes',
        sizes: ['P', 'M', 'G'],
        material: 'Algodão fio 40.1',
        colors: ['Preto', 'Branco'],
        coupon: 'KANGAR10',
        stock: 30,
        tags: ['t-shirt', 'jujutsu kaisen', 'logo', 'camisas', 'anime', 'nerd', 'preta', 'branca']
    },
    {
        id: 'tshirt-26',
        image: 'Imagens/Fotos Camisas/tshirt-saitama.png', 
        name: 'T-Shirt Naruto - Ichiraku Ramen',
        price: 94.90,
        rating: 4.8,
        reviews: 230,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão fio 40.1',
        colors: ['Branco', 'Preto', 'Bege'],
        coupon: 'KANGAR10',
        stock: 22,
        tags: ['t-shirt', 'naruto', 'ramen', 'ichiraku', 'camisas', 'anime', 'geek', 'branca', 'preta']
    },
    {
        id: 'tshirt-27',
        image: 'Imagens/Fotos Camisas/tshirt-draken.png', 
        name: 'T-Shirt Spy x Family - Anya',
        price: 89.90,
        rating: 4.7,
        reviews: 110,
        collection: 'Animes',
        sizes: ['PP', 'P', 'M', 'G'],
        material: 'Algodão fio 40.1',
        colors: ['Rosa', 'Branco', 'Preto'],
        coupon: 'KANGAR10',
        stock: 15,
        tags: ['t-shirt', 'spy x family', 'anya', 'camisas', 'anime', 'nerd', 'branca', 'preta']
    },
    {
        id: 'hoodie-28',
        image: 'Imagens/Fotos Camisas/hoodie-akatsuki.png', 
        name: 'Hoodie Bleach - Divisões Gotei 13',
        price: 189.90,
        rating: 4.8,
        reviews: 90,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Moletom 3 cabos (Algodão/Poliéster)',
        colors: ['Preto', 'Branco'],
        coupon: 'KANGAR10',
        stock: 10,
        tags: ['hoodie', 'moletom', 'bleach', 'gotei 13', 'anime', 'geek', 'preta', 'branca']
    },
    {
        id: 'tshirt-29',
        image: 'Imagens/Fotos Camisas/tshirt-guts.png', 
        name: 'T-Shirt One Piece - Zoro',
        price: 94.90,
        rating: 4.9,
        reviews: 350,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG', 'XG'],
        material: 'Algodão fio 40.1',
        colors: ['Verde', 'Preto', 'Branco'],
        coupon: 'KANGAR10',
        stock: 30,
        tags: ['t-shirt', 'one piece', 'zoro', 'roronoa', 'camisas', 'anime', 'nerd', 'preta', 'branca']
    },
    {
        id: 'tshirt-30',
        image: 'Imagens/Fotos Camisas/tshirt-killua.png', 
        name: 'T-Shirt Samurai Champloo - Mugen',
        price: 99.90,
        rating: 4.7,
        reviews: 88,
        collection: 'Animes',
        sizes: ['P', 'M', 'G', 'GG'],
        material: 'Algodão Egípcio',
        colors: ['Preto', 'Bege'],
        coupon: 'KANGAR10',
        stock: 12,
        tags: ['t-shirt', 'samurai champloo', 'mugen', 'jin', 'camisas', 'vintage', 'anime', 'geek', 'preta']
    }
];
